### ISSUE TITLE
Error when entering "families" in a (single) given record

### ISSUE THREAD

**Issue by BernatBanyuls** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#84]
Greetings.

I have detected the following problem in one of my logs. 

Could you help me to solve it.

Thank you.

(It only happens in one log: I probably did something wrong in my haste, but I don't know what happened and how to fix it.

![image](https://user-images.githubusercontent.com/103060233/191779093-eafe17f6-5b22-4a29-828b-a98b445dd0fb.png)

Archivo GEDCOM.

![image](https://user-images.githubusercontent.com/103060233/191778195-b4be0121-1794-465a-a95c-e39e315d8ec0.png)

I have the webtrees and modules updated. I have not added anything new.

**Comment by ric2016** [comment]
There is definitely a missing null check in that part of the code.

However it is a bit unexpected to encounter it at this point, I'm not sure what exactly causes the inconsistency. Do you have any special privacy rules in for this individual, or related individuals? Do you have inconsistent GEDCOM data? (anything suspicious when using "Check for errors" on the tree via the control panel?)

In any case, can you check whether the problem is resolved after replacing the file 'RelationshipPath.php' with the updated version from [this commit](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/commit/bfffceede46c8e6008291777fe39d50ef5aeb264)?

**Comment by BernatBanyuls** [comment]
Greetings Ric.

I have not been able to continue with the problem so far.

What I have done is to delete each GEDCOM record one by one until I got the problem to go away. Once this was achieved, I re-registered the data and everything works correctly.

I think the problem was in the child record. As I didn't know the parents, I put fictitious names and maybe there was an error or duplicity that caused the problem. Now everything works correctly.  If the error (or any other) appears again, I will let you know.

Thanks for everything.


Translated with www.DeepL.com/Translator (free version)

**Comment by ric2016** [comment]
In any case these kinds of errors (likely caused by inconsistent GEDCOM) should no longer occur with the latest Vesta release.
